name: Print hello world
description: "This action is to print hello world"

inputs:
  enable_fib:
    description: "This will enable fibonacci"
    required: false
    default: "true"

  max_threshold:
    description: "This is the max value of the fibonacci"
    required: false
    default: "180"

  users:
    description: "The user should parse his own value but it should not be greater than the max_threshold"
    required: true

  runs:
    using: "docker"
    image: "Dockerfile"
    env:
      ENABLE_FIB: ${{ inputs.enable_fib }}
      MAX_THRESHOLD: ${{ inputs.max_threshold }}
      USERS: ${{ inputs.users }}
    entrypoint: /usr/local/bin/fibbot