name: Print hello world
description: "This action is to print hello world"

inputs:
  pr_num:
    description: "This is to get the current pull page number"
    required: true
    default: "1"
    
  enable_fib:
    description: "This will enable fibonacci"
    required: false
    default: "true"
    
  users_input:
    description: "User manually enters the input and it should not be greater than the max_threshold"
    required: false
    default: "0"

  max_threshold:
    description: "This is the max value of the fibonacci"
    required: true
    default: "180"
    
  github_token:
    description: "GitHub token to interact with GitHub API"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.pr_num }}
    - ${{ inputs.enable_fib }}
    - ${{ inputs.users_input }}
    - ${{ inputs.max_threshold }}
    - ${{ inputs.github_token }}
