name: Print hello world
description: "This action is to print hello world"

inputs:
  github_token:
    description: "Adding my token"
    required: true
    default: "empty"

  enable_fib:
    description: "This will enable fibonacci"
    required: true
    default: "true"
    
  users_input:
    description: "User manually enters the input and it should not be greater than the max_threshold"
    required: false
    default: "0"

  max_threshold:
    description: "This is the max value of the fibonacci"
    required: true
    default: "180"
  
  # This argument here will help me to get the pull request number and pass it as the 4th argument
  pr_num:
    description: "This is to get the current pull page number"
    required: true
    default: "1"
    # This one will cause my docker file to be exercuted
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.github_token }}
    - ${{ inputs.enable_fib }}
    - ${{ inputs.users_input }}
    - ${{ inputs.max_threshold }}
    - ${{ inputs.pr_num }}
