name: Print Hello World
on:
    push:
        branches:
            - main

jobs:
    run-hello-world:
        runs-on: ubuntu-latest
        steps:
            # This will Check my repository to see if it is running
            -   name: Checkout Repository
                uses: actions/checkout@v3
            
            -   name: Exercute Custorm Action
                uses: ./
                with:
                    runs: "composite"
            
            -   name: Cached Cargo registry and build
                uses: actions/cache@v4
                with:
                    path: |
                        ~.cargo/bin/
                        ~/.cargo/registry/index/
                        ~/.cargo/registry/cache/
                        ~.cargo/.git/db/
                        target
                    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-cargo-


        
        
