name: Print Hello World
on:
    push:
        branches:
            - main

jobs:
    run-hello-world:
        runs-on: ubuntu-latest
        steps:
            # This will Check my repository to see if it is running
            -   name: Checkout Repository
                uses: actions/checkout@v3
            
            -   name: Exercute Custorm Action
                uses: ./
                with:
                    runs: "composite"

        
        
