name: Print Hello World
on:
# This one is to make the workflow to be triggered on a pull request from a fork fork  
    pull_request_target:
        types: [opened, edited]
        branches:
            - 'main'
            - '**'
# This will be triggered an pull request but not a fork
    pull_request:
        types: [opened, edited]
        branches:
            - 'main'
            - '**'
    push:
        branches: 'main'
# This will give github action the permission to write on pull requests which is what we need to do writing a comment but before this 
# We need to go to our github settings and and under actions we give some read and write permisions
permissions:
    pull-requests: write
    contents: read

jobs:
    run-hello-world:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
            repository-projects: write
        steps:
            # This will Check my repository to see if it is running
            -   name: Checkout Repository
                uses: actions/checkout@v4
            # This is to prevent your workflow from building from scratch but to build only file that have being updated
            -   name: Cached Cargo registry and build
                uses: actions/cache@v4
                with:
                    path: |
                        ~.cargo/bin/
                        ~/.cargo/registry/index/
                        ~/.cargo/registry/cache/
                        ~.cargo/.git/db/
                        target
                    key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-cargo-
                        
            -   name: Exercute Custorm Action Created By Richmond
                uses: ./
                with:
                    runs: "composite"
                    
            -   name: Run My action with these other arguments [_,true]
                uses: ./
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    enable_fib: "true"
                    users_input: "25"
                    max_threshold: "158"
                    pr_num: ${{ github.event.pull_request.number }}
                   

            -   name: Run with 150 and enable status true
                uses: ./
                with:
                    github_token: ${{ secrets.GITHUB_TOKEN }}
                    enable_fib: "true"
                    users_input: "28"
                    max_threshold: "150"
                    pr_num: ${{ github.event.pull_request.number }}
                    
                
                    

                   
                    
            



        
        
